#!usr/bin/python3

#Usage: ./analysis.py WIKIPARSED MOST_IN 
# WIKIPARSED is the parsed wikipedia file generated by the parse script
# LINKEDTO is file where we rank each page in order of most incoming links

import networkx as nx
import sys

g = nx.DiGraph()

if len(sys.argv) < 3: 
  print("Usage: ./grapher.py WIKIPARSED LINKEDTO")
  exit(1)

#open file
input_file = open(sys.argv[1], 'r')

current_node = ""
while True:
  line = input_file.readline().strip()
  #if it starts with <title>, it's a title
  if not line: break
  #if it starts with brackets, it's a link from <currentpage>
  if line[0] == "[":
    line = line[2:-2] #[[ = 2, ]] = 2
    g.add_edge(line, current_node)
  elif line[0] == "<":
    line = line[7:-8] # <title> = 7, </title> = 8
    current_node = line

most_in_links = {node:len(g.in_edges(node)) for node in g.nodes()}
in_sorted = sorted(most_in_links.items(), key=lambda kv: kv[1], reverse=True)
in_file = open(sys.argv[3], 'w')
for x in in_sorted:
  in_file.write(str(x) + "\n")
in_file.close()




